---
- name: docker
  hosts: web
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  roles:
  - docker-{{ansible_facts['os_family']}}
  - { role: docker-redhat, when: ansible_facts['distribution'] == 'Redhat' }
  - { role: docker-ubuntu, when: ansible_facts['distribution'] == 'Ubuntu' }