---
    - name: install docker
      include_tasks: "{{ansible_distribution}}.yml"

    - name: add additional users to docker group
      user:
        name: '{{ item }}'
        groups: docker
        append: yes
      with_items: '{{ docker_group_members }}'
      when: docker_group_members is defined