---
- name: Install required system packages
  yum: name={{ item }} state=latest
  with_items:
   - 'yum-utils'
   - 'device-mapper-persistent-data'
   - 'lvm2'
   - 'ca-certificates'
   - 'curl'

- name: Add Docker GPG key.
  rpm_key:
    key: "{{ Redhat_Docker_GPG_key }}"
    #key: https://download.docker.com/linux/centos/gpg
    state: present
    
- name: Add Docker repo
  get_url:
    url: "{{ Redhat_Docker_repo }}"
    #url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes 

- name: install the containerd.io rpm from a remote repo
  yum:
    name: "{{ Redhat_containerdio_url }}"
    #name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present

- name: Update yum and install docker-ce
  yum: name=docker-ce state=latest
  notify:
    - restart docker

- name: add users to docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_items: '{{ docker_group_members }}'
  when: docker_group_members is defined