---
- name: Install required system packages
  yum: name={{ item }} state=latest
  with_items:
   - 'yum-utils'
   - 'device-mapper-persistent-data'
   - 'lvm2'
   - 'ca-certificates'
   - 'curl'

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
    
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes 

- name: Add Docker repository.
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    #owner: root
    #group: root
    #mode: 0644

- name: install the containerd.io rpm from a remote repo
  yum:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present

- name: Update yum and install docker-ce
  yum: name=docker-ce state=latest
  notify:
    - restart docker

- name: add to docker group
  user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
    with_items: "{{ users }}"